Add pcov driver for coverage
Also refactors config into commands/executors to allow
easier addition/refactoring in the future

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -2,70 +2,104 @@
 #
 # Check https://circleci.com/docs/2.0/language-php/ for more details
 #
-version: 2
-jobs:
-  build:
+version: 2.1
+
+executors:
+  docker-executor:
     docker:
-      - image: silverstripe/bespoke-ci-base:3.0.0
+      - image: ghcr.io/silverstripeltd/bespoke-ci-base:3.2.0
         environment:
-          - DISPLAY=:99
-          - CHROME_BIN=/usr/bin/google-chrome-stable
-          - BASH_ENV=/root/.bashrc
+          DISPLAY: :99
+          CHROME_BIN: /usr/bin/google-chrome-stable
+          BASH_ENV: /root/.bashrc
       - image: circleci/mysql:5.7
         environment:
-          - MYSQL_ROOT_PASSWORD=ubuntu
-          - MYSQL_DATABASE=circle_test
-          - MYSQL_HOST=127.0.0.1
-
+          MYSQL_ROOT_PASSWORD: ubuntu
+          MYSQL_DATABASE: circle_test
+          MYSQL_HOST: 127.0.0.1
     working_directory: /var/www/mysite/www
 
+commands:
+  background-services:
+    description: Start Apache, Nginx and Xvfb
     steps:
-
-      # Update and add dependency for Cypress
-      - run:
-          name: Update and add dependency for Cypress v6
-          command: |
-            rm /etc/apt/sources.list.d/mysql_56.list
-            rm /etc/apt/sources.list.d/php_sury.list
-            apt-get update
-            apt-get install -y libgbm-dev
-
-      # Use correct php version
-      - run: php-switch 7.4
-
-      # Start Apache, Nginx and Xvfb
-      - run: sudo service apache2 start
-      - run: sudo service nginx start
       - run:
           command: Xvfb :99 -screen 0 1280x1024x24
           background: true
-
-      - checkout
-
-      # Use correct node version
-      - run: nvm alias default $(cat .nvmrc)
-
+      - run: sudo service apache2 start
+      - run: sudo service nginx start
+  dependencies:
+    description: Install dependencies
+    steps:
       # Composer Cache + Installation
       - restore_cache:
           keys:
             - v1-composer-{{ checksum "composer.lock" }}
             # fallback to using the latest cache if no exact match is found
             - v1-composer-
-      - run: composer install -n --prefer-dist
+      # prefer source composer install to make test files available
+      - run: composer install -n --prefer-source --no-interaction
       - run: composer vendor-expose # always expose: cached content is never exposed automatically
-      # Save all dependancies to cache
+      # Save all dependencies to cache
       - save_cache:
           key: v1-composer-{{ checksum "composer.lock" }}
           paths:
             - vendor
             - resources
 
-      # NPM Installation
-      # We don't cache the installed files as it takes longer to restore the cache than
-      # it does to run a fresh install
-      - run: yarn install
+      # NPM Cache + Installation
+      - restore_cache:
+          keys:
+            - v1-npm-deps-{{ checksum "yarn.lock" }}
+      - run: yarn install --frozen-lockfile
+      - save_cache:
+          paths:
+            - ./node_modules
+            - /root/.cache/Cypress
+          key: v1-npm-deps-{{ checksum "yarn.lock" }}
+  php-tests:
+    description: phpunit tests
+    parameters:
+      coverage:
+        type: boolean
+        default: true
+    steps:
+      - run:
+          name: phpunit
+          command: |
+            phpdismod xdebug
+            PHPUNITARGS=""
+            if << parameters.coverage >>;
+            then
+                phpenmod -v 7.4 pcov
+                vendor/bin/pcov clobber
+                PHPUNITARGS=" --coverage-html coverage/php  --coverage-clover coverage/php/clover.xml"
+            fi
+            vendor/bin/phpunit --verbose $PHPUNITARGS
+  js-tests:
+    description: JS/Vue Tests
+    steps:
+      - run: yarn test:app
+  e2e-tests:
+    description: JS E2E tests
+    steps:
+      - run: yarn test:e2e
+jobs:
+  build:
+    executor: docker-executor
 
+    steps:
+      - checkout
+      # Use correct php version
+      - run: php-switch 7.4
+      # Use correct node version
+      - run: nvm alias default $(cat .nvmrc)
       - run: mv .circleci/.env.circleci .env
+
+      - background-services
+      - dependencies
+
+      # setup permissions
       - run: chown -R vagrant:vagrant /var/www/mysite/www
       - run: chmod g+s /var/www/mysite/www/public
 
@@ -79,20 +113,22 @@ jobs:
       # dev/build
       - run: sudo -u vagrant vendor/bin/sake dev/build flush=1
 
-      # PHP Tests
-      - run: vendor/bin/phpunit --verbose --coverage-html coverage/php  --coverage-clover coverage/php/clover.xml
-
-      # Vue Tests
-      - run: yarn test:app
-
-      # JS E2E tests
-      - run: yarn test:e2e
+      # run test suites
+      - php-tests
+      - js-tests
+      - e2e-tests
 
       # Generate coverage reports
       - run: yarn test:coverage
 
       # Requires $CODECOV_TOKEN variable set in CircleCI
-      - run: bash <(curl -s https://codecov.io/bash)
+      - run:
+          name: Send coverage to codecov.io
+          command: |
+            curl -s https://codecov.io/bash > codecov;
+            VERSION=$(grep 'VERSION=\".*\"' codecov | cut -d'"' -f2);
+            shasum -a 512 -c  <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/${VERSION}/SHA512SUM | grep codecov);
+            bash <(cat codecov) || echo "Codecov submission failed, check https://status.codecov.io"
 
       - store_artifacts:
           path: cypress/screenshots
